## Load in Numpy (Pip install numpy for installation)

In [1]:
import numpy as np

## Basics

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[2.0, 3.0, 4.0], [5.0, 6.0, 7.0]])
print(b)

[[2. 3. 4.]
 [5. 6. 7.]]


In [6]:
#Get dimension for 'a' using ndim
a.ndim

1

In [7]:
#Get dimension for 'b' using ndim
b.ndim

2

In [13]:
# Get the shape for 'a'
a.shape

(3,)

In [14]:
# Get the shape for 'b'
b.shape

(2, 3)

In [15]:
# Get type for 'a'
a.dtype

dtype('int32')

In [16]:
# Get type for 'b'
b.dtype

dtype('float64')

In [19]:
#Get size
a.itemsize

4

In [20]:
#Get size
b.itemsize

8

In [21]:
#Get total size
a.size *a.itemsize

12

## Acessing or changing specific elements, rows, columns, etc

In [23]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
# Get a specific element [r, c]  - the array above indicate that it starts as row 0 and row 1 and column 1 to column 7
a[1, 5]  #row 1 and column 5 will produce 13

13

In [25]:
#Get a specific row
a[0, :]   #row 0 with all columns

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
#Get a specific row
a[1, :]   #row 1 with all columns

array([ 8,  9, 10, 11, 12, 13, 14])

In [28]:
#Get a specific column
a[:, 2] #all rows with values in column 2 of each row

array([ 3, 10])

In [29]:
#Getting a little more fancy(row, startindex:endindex:stepsize)
a[0, 1:-1:2]

array([2, 4, 6])

In [30]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### *3-d Example

In [35]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
# Get specific element (work outside in)
b[0,1,1]  #meaning first matrix, second row second column 

4

In [42]:
# Get specific element (work outside in)
b[:,1,:]  #meaning first matrix, second row second column 

array([[9, 9],
       [8, 8]])

In [39]:
# Get specific element (work outside in)
b[:,0,:]  #meaning first matrix, second row second column 

array([[1, 2],
       [5, 6]])

In [43]:
#replace
b[:,1,:] = [[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initializing Different Type of Arrays

In [44]:
# all of zeros matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [46]:
# all of zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
# all of zeros matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [48]:
# all of ones matrix
np.ones(3)

array([1., 1., 1.])

In [49]:
# all of ones matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [50]:
np.ones((2,3,3,2))

array([[[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]])

In [53]:
# all of ones matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [54]:
# any other number
np.full((2,2), 99) #means 2 by 2 matrix and should be filled with 99

array([[99, 99],
       [99, 99]])

In [55]:
# any other number
np.full((2,2), 99, dtype = 'float32') #means 2 by 2 matrix and should be filled with 99 in float

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [56]:
#any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [57]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.07465683, 0.05657932],
       [0.36706274, 0.65012327],
       [0.39143984, 0.79648189],
       [0.98846279, 0.51065662]])

In [58]:
#Random decimal numbers
np.random.random_sample(a.shape)

array([[0.00435129, 0.47919555, 0.9988164 , 0.8266058 , 0.21438222,
        0.26490101, 0.83531535],
       [0.91239581, 0.84831352, 0.5531611 , 0.29846984, 0.12671961,
        0.94390959, 0.12747375]])

In [59]:
#random integer values
np.random.randint(7)

5

In [60]:
#random integer values
np.random.randint(7, size=(3,3))

array([[1, 5, 3],
       [6, 3, 5],
       [0, 0, 1]])

In [61]:
#random integer values
np.random.randint(4,8, size=(3,3))

array([[4, 4, 6],
       [6, 6, 7],
       [4, 4, 5]])

In [62]:
#random integer values
np.random.randint(-4,8, size=(3,3))

array([[-1,  3,  5],
       [ 2, -1, -1],
       [ 5,  7,  6]])

In [63]:
#The Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
#repeat 'a' array three times (3x)
arr=np.array([[1,2,3]]) #tuple
r1=np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [65]:
#repeat 'a' array three times (3x)
arr=np.array([1,2,3]) # not tuple
r1=np.repeat(arr, 3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [70]:
output = np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Be careful when copying arrays!!!

In [72]:
a = np.array([1,2,3])
b=a
b[0] = 100

print (a) #disadvantage that 'a' changed because a seperate copy wasn't made for 'b' so it overwrite the initial message of b

[100   2   3]


In [73]:
print(b)

[100   2   3]


### Mathematics

In [81]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [82]:
a + 2

array([3, 4, 5, 6])

In [83]:
a - 2

array([-1,  0,  1,  2])

In [84]:
a += 2
a

array([3, 4, 5, 6])

In [85]:
a ** 2

array([ 9, 16, 25, 36], dtype=int32)

In [86]:
a/2

array([1.5, 2. , 2.5, 3. ])

In [87]:
a * 2

array([ 6,  8, 10, 12])

In [88]:
b =np.array([1,0,1,0])
a + b

array([4, 4, 6, 6])

In [90]:
# Take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [91]:
# Take the cos
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [89]:
# Take the tan
np.tan(a)

array([-0.14254654,  1.15782128, -3.38051501, -0.29100619])

### Linear Algebra

In [92]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)  #create a 3 * 2 matrix and fill it with 2
print(b)

np.matmul(a,b) # multiply 'a' by 'b'

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [93]:
#find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [94]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
np.min(stats)

1

In [96]:
np.max(stats)

6

In [97]:
np.min(stats, axis =0)

array([1, 2, 3])

In [98]:
np.min(stats, axis =1)

array([1, 4])

In [99]:
np.max(stats, axis =0)

array([4, 5, 6])

In [100]:
np.max(stats, axis =1)

array([3, 6])

### Reorganizing Arrays

In [102]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [103]:
after1 = before.reshape((4,2))
print(after1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [104]:
after2 = before.reshape((8,1))
print(after2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [105]:
after = before.reshape((2,3))  #this will produce value error because the array of size 8 doesn't match with the shape (2,3)
print(after)

ValueError: cannot reshape array of size 8 into shape (2,3)

### vertically stacking vectors

In [108]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [109]:
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

### Horizontal stacking vectors

In [111]:
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])
h1
h2
np.hstack([h1,h2])


array([1, 2, 3, 4, 5, 6, 7, 8])

In [113]:
h1 = np.ones([2,4])
h2 = np.zeros([2,2])
h1



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [115]:
h2


array([[0., 0.],
       [0., 0.]])

In [116]:
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

In [118]:
# Load data from file
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [123]:
filedata.astype('int32') # put all value in integer datatype
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


###Boolean Masking and Advanced Indexing

In [124]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [125]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [127]:
# You can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [129]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [130]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [131]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [132]:
(filedata > 50) & (filedata < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [133]:
(~(filedata > 50) & (filedata < 100)) # ~ means 'not'

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])